### ISSUE TITLE
teacher can view after restriction 

### ISSUE THREAD

**Issue by abarakeh** [moodle-an-hochschulen/moodle-availability_role#23]
Hello , 

i install this plugin on moodle 4.1

Restriction by course role
[Moodle plugins directory: Restriction by course role](https://moodle.org/plugins/availability_role)

i'm moodle admin i want to add file inside thw course i want just only student can view this file, 

this plugin don't need any configuration but it's not working 

after i add the file and make restriction for who can view i select it's available just only for students and hidden otherwise
but still the instructor can view it ?

can you help me !!
Thanks

**Comment by abias** [comment]
Hi @abarakeh ,

I am sorry to tell you but this is a situation where the plugin is not really guilty, it's a matter of the teacher role.
An improvement proposal has been filed long ago on #16, but has not been realized yet.

Cheers,
Alex
